### ISSUE TITLE
tracking issue: GEODE SUPPORT (& more)

### ISSUE THREAD

**Issue by RoootTheFox** [RoootTheFox/Linux-MegaHack-Installer#13]
MegaHack [added support for Geode](https://twitter.com/absolllute/status/1749262979864908197) a couple days ago, and since Geode will be the way GD modding is gonna go forward, I will be adding support for installing Geode to this script.

### What is Geode??
[Geode](https://geode-sdk.org/) is a modloader for Geometry Dash that aims to end mod incompatibilities and make updating to newer GD versions easier and faster for modders.
**If you are a modder (somehow)**, it is encouraged to port your existing mods to Geode.

### TODO
- [ ] support GD installations on external drives (Proton / GD not inside main Steam folder)
- [x] #20
- [ ] option to select an install between **plain Geode**, **Geode with MH**, or **Vanilla MegaHack** (this will probably be used for updating too)
- [ ] rebrand of the script/repo (to reflect that it also supports Geode)

**Comment by theonekingboo** [comment]
cool i was thinking about this after the change

**Comment by RoootTheFox** [comment]
[Geode has an official Linux installer script](https://geode-sdk.org/install): `curl -o- 'https://geode-sdk.org/install/linux.sh' | bash`
